"""CodeAgent package"""

from .agent import CodeAgent, get_agent, set_agent
from .core import Config, get_config, set_config, LLMClient, get_client, set_client
from .context import load_memory, save_memory, load_rules, load_skills, HistoryManager
from .utils import (
    console,
    print_info,
    print_success,
    print_warning,
    print_error,
    print_tool_call,
    print_step,
    print_result,
    print_markdown,
    print_syntax,
    print_table,
    print_tree,
    print_panel,
    print_header,
    print_footer,
    create_progress,
    Spinner,
    StatusDisplay,
    confirm,
    input_text,
    print_agent_intro,
    CLI,
    run_cli,
)

__version__ = "0.2.0"

__all__ = [
    "CodeAgent",
    "get_agent",
    "set_agent",
    "Config",
    "get_config",
    "set_config",
    "LLMClient",
    "get_client",
    "set_client",
    "load_memory",
    "save_memory",
    "load_rules",
    "load_skills",
    "HistoryManager",
    "console",
    "print_info",
    "print_success",
    "print_warning",
    "print_error",
    "print_tool_call",
    "print_step",
    "print_result",
    "print_markdown",
    "print_syntax",
    "print_table",
    "print_tree",
    "print_panel",
    "print_header",
    "print_footer",
    "create_progress",
    "Spinner",
    "StatusDisplay",
    "confirm",
    "input_text",
    "print_agent_intro",
    "CLI",
    "run_cli",
]
